project:
  type: website
  output-dir: docs

website:
  title: "Brock Lab Website"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Guide"
        contents:
          - guide/markdown.qmd
          - guide/computations.qmd
          # Add more sidebar items

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


